# Vectors

In [7]:
import numpy as np
v = np.array([[1],[2],[3]])
v2 = np.array([[-1],[-2],[-3]])

In [12]:
print(v)

[[1]
 [2]
 [3]]


In [13]:
print(v.T)

[[1 2 3]]


In [2]:
v.shape

(3, 1)

# Matrices

In [5]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
M.shape

(3, 3)

In [8]:
#Scalar 
x = 3.5
new_matrix = list(zip(v,v2))

In [9]:
new_matrix

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [10]:
type(new_matrix)

list

# dot product
we use the dot product to multiply two dectors. In 2D vectors this is the same as matrix multiplication. Produces a scalar value (a number, not a vector) that says the degree to which the two vectors interact. Interaction between similar dimensions. 

WHy do we care? solar panel tracking, force diagrams, rendering 

In [14]:
np.dot(v.T, v)

array([[14]])

In [17]:
#can think of this as 
north = np.array([0,1])
east = np.array([1,0])

#to what degree are north and east the same?
np.dot(north,east)



0

In [19]:
#Create an example for north and south. So, in other words: find the dot product of north and south.
north = np.array([0,1])
south = np.array([0,-1])

np.dot(north, south)

1

# Cross product 

type of vector multiplication also, but it shows the interaction between different components as expressed by a vector. It tracks all the cross interactions between dimensions.

Performing the cross product results in a new vector that is perpendicular to both the input vectors.

why do we care? torque and "moment of a force" 

In [20]:
np.cross(v, v2, axisa=0, axisb=0).T

array([[0],
       [0],
       [0]])

In [21]:
v

array([[1],
       [2],
       [3]])

In [22]:
v2

array([[-1],
       [-2],
       [-3]])

# Orthogonality

Two vectors are orthogonal if theyre perpendicular to eachother. The dot product is what? 0 or the identity matrix.

$$ A \cdot A^T = I $$

In [24]:
M = np.array([[1,0,0],
             [0,1,0],
             [0,0,1]])
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
#we know its orthogonal because it produces an identity matrix
np.dot(M,M.T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
#Can you come up with another orthogonal matrix?

#This one is not
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(M,M.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])