In [5]:
class Music:
    @staticmethod
    def play():
        print("*playing music*")

    def stop(self):
        print("stop playing")

Music.play()
album = Music()
#Music.stop(album)
album.stop()

*playing music*
stop playing


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a)
print(a.ndim, a.shape, a.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
2 (2, 3) float32


In [12]:
b = np.array([1,2,3,4],ndmin = 4)

In [13]:
b

array([[[[1, 2, 3, 4]]]])

In [16]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [15]:
c.shape

(1, 4, 3)

In [22]:
def mathematics(a,b):
    addition= a + b
    print(str(a) + "+" +  str(b) + "= " + str(addition))
    subtraction = a - b
    print(str(a) + "-" + str(b) + "=" + str(subtraction))
    product = a * b
    print(str(a) + "*" + str(b) + "=" + str(product))
    if addition ==0 or subtraction ==0 or product ==0:
        print("zero")

In [23]:
mathematics(3,6)

3+6= 9
3-6=-3
3*6=18
