In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a = a.reshape(3,2)
#a = a.reshape(2,-1)
#a = a.ravel()

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.arange(10).reshape(5,2)
#a = a.T
#a = a.transpose((1,0))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a = a.T
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
a = a.transpose((1,0))
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [17]:
a[0,0]  # top-left element
#a[0,-1]  # first row, last column
#a[0,:] # first row (many entries)
#a[:,0] # first column (many entries)

0

In [18]:
a[0,-1]

8

In [19]:
a[0,:]

array([0, 2, 4, 6, 8])

In [20]:
a[:,0]

array([0, 1])

In [23]:
a[:,1:3]

array([[2, 4],
       [3, 5]])

In [24]:
a[:,1:4:2]

array([[2, 6],
       [3, 7]])

In [26]:
a = list(range(10))
print(a)
a[:3] # indices 0, 1, 2
a[-3:] # indices 7, 8, 9
a[3:8:2] # indices 3, 5, 7
a[4:1:-1] # indices 4, 3, 2 (this one is tricky)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
b = np.random.randint(2,11,size=(3,3))
#b = np.arange(2,11).reshape(3,3)
b

array([[10,  8,  9],
       [ 5, 10,  9],
       [ 2, 10,  7]])

In [33]:
a = np.sqrt(b)
a

array([[3.16227766, 2.82842712, 3.        ],
       [2.23606798, 3.16227766, 3.        ],
       [1.41421356, 3.16227766, 2.64575131]])

In [34]:
import pandas as pd

my_list=[100,200,400,600,900]
my_series = pd.Series(my_list)
my_series

0    100
1    200
2    400
3    600
4    900
dtype: int64